apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j7zf0jk68-python
  janus-idp.io/tekton: j7zf0jk68-python
  backstage.io/kubernetes-id: j7zf0jk68-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j7zf0jk68-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
